version: "3.9"
services:
  db:
    image: postgres:12.8
    container_name: hackathon-db
    restart: "no"
    ports:
      - 5432:5432
    volumes:
      - ./src/sql/scripts.sql:/docker-entrypoint-initdb.d/scripts.sql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=hackathon
  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - "15432:80"
    environment:
      - GUNICORN_THREADS=1
      - PGADMIN_DEFAULT_EMAIL=hackathon@fortna.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    depends_on:
      - db
  backend:
    image: openjdk:8
    container_name: hackathon-be
    restart: "no"
    ports:
      - 8088:8088
    volumes:
      - ./target/simple-web-0.0.1-SNAPSHOT.jar:/home/hackathon-be.jar
      - ./data:/data
      - ./logs:/logs
    environment:
      - CONNECTION_URL=jdbc:postgresql://hackathon-db:5432/hackathon
      - CONNECTION_USERNAME=root
      - CONNECTION_PASSWORD=root
      - GAME_DIR=/data
    command: bash -c "java -jar /home/hackathon-be.jar --spring.datasource.url=$${CONNECTION_URL} --spring.datasource.username=$${CONNECTION_USERNAME} --spring.datasource.password=$${CONNECTION_PASSWORD} --file.game-dir=$${GAME_DIR}"
    depends_on:
      - db